### ISSUE TITLE
Check indentation only for lines starting with HTML tags

### ISSUE THREAD

**Issue by debjitbis08** [htmllint/htmllint#117]
Came across an issue while linting the below piece of code. I have set `indent-width: 4` but since the placeholder attribute is indented with 7 spaces, an error is thrown.

```html
<form ng-submit="todoList.addTodo()">
    <input type="text" ng-model="todoList.todoText" size="30"
           placeholder="add new todo here">
    <input class="btn-primary" type="submit" value="add">
</form>
```

If we have an option such that only lines starting with HTML tags will be checked for indentation, then the attributes can be indented in custom ways.

**Comment by KrekkieD** [comment]
This is called `continuation indent` in my IDE. I personally prefer a +4 indent, others like to align the attributes as shown in this example. These settings could be used in the rule value.

**Comment by mlochbaum** [comment]
It does make sense to have this option, and it should probably be a boolean option separate from `indent-style` but pertaining to the same rule. Since indentation is checked on the raw text rather than parsed html, it's not possible exactly to test whether a line starts with a tag. But testing whether it starts with `<` should be sufficient.

**Comment by mlochbaum** [comment]
New option `indent-width-cont` does this. Set it to true, and lines whose first non-whitespace character is not `<` will not give indent width errors.
