### ISSUE TITLE
tag-self-close should ignore menuitem when it has a closing tag

### ISSUE THREAD

**Issue by erikvold** [htmllint/htmllint#139]
At the moment if I set `tag-self-close` to `true` then it will error on this code:

`<menuitem>Do Thing</menuitem>`

and it should not do this if there is a closing tag, as there is in this case.

The error is this:

> void element should close itself

It would be nice if there was an exclude option for this rule too, like there appear to be for other rules.

**Comment by mlochbaum** [comment]
I think you've misunderstood something about the html spec here (and this is a very confusing part of html, so that's not too surprising).

`menuitem` is a void element, meaning (1) it should not contain any content and (2) the closing tag may (and should, generally) be omitted. So your example should perhaps be `<menuitem label="Do Thing">`. The htmllint option `tag-self-close` is used to require all void elements to be self-closing (like `<br/>`, for example). This was the preferred style in html4. However, it is not typically used in html5, and `menuitem` is _only_ defined in html5. So it seems that you should just not be using `tag-self-close`.

A rule to exclude certain elements seems strange because html has only exactly list of void elements, and they behave the same. It would be very unusual to require code to style some of them differently than others.

**Comment by erikvold** [comment]
Ah ok, I'll switch to using `ul`/`li` then.
