### ISSUE TITLE
attr-quote-style not enforced on a empty unquoted value

### ISSUE THREAD

**Issue by reviling** [htmllint/htmllint#159]
Example: 'attr-quote-style' is set to 'double'.

`<blah someAttr=''>` returns: (E005), the `someAttr` attribute is not double quoted

However...

`<blah someAttr=>` returns no error. I expect this to return an error since it is not double quoted.

Furthermore, `<blah someAttr=>` could possibly return an error since it looks like it's trying to assign the '>' character to 'someAttr'.

RE: https://www.w3.org/TR/html-markup/syntax.html#syntax-attributes

> **Attribute names** must consist of one or more characters other than the space characters, U+0000 NULL, """, "'", ">", "/", "=", the control characters, and any characters that are not defined by Unicode.

Regardless, something funky is going on.

**Comment by mlochbaum** [comment]
Setting `attr-req-value` will give you error E006 "attribute values cannot be empty" for `<blah someAttr=>`. This option is on by default.

The parser doesn't distinguish between attributes with an `=` but no value and those without either in its output. This means that returning E005 for attributes with `=` will also give false positives for boolean attributes (e.g. `checked` for a checkbox). See #92. It may be possible to fix this but it would be pretty difficult, and I haven't looked into it seriously.

**Comment by mlochbaum** [comment]
Thanks to commit a3f98090, it's now possible to implement this by checking that `attr.rawEqValue` is nonempty instead of `attr.rawValue`. However, I've decided that it's not good design to give both E005 and E006 on every empty value. Markup like `<blah someAttr=>` is hardly a quoting issue--it's invalid html!

I have added some clarifications to the wiki and am closing this issue. Feel free to comment if you disagree with the stance I took.
