### ISSUE TITLE
tag-self-close in documentation is actually tags-self-close

### ISSUE THREAD

**Issue by MichaelManhire** [htmllint/htmllint#169]
If you have `"tag-self-close": "never"` in your configuration and `<img>` in your HTML, then it returns an error: `void element should close itself`.

However, if you have `"tags-self-close": "never"` (plural tags instead of singular tag) in your configuration, then it works as expected and `<img>` won't return an error.

The documentation says that the key is supposed to be `tag-self-close` even though that doesn't work. Either the documentation should be updated, or `tags-self-close` should be changed to `tag-self-close` in the code.

**Comment by mlochbaum** [comment]
The option "always" for `tag-self-close` specifies that void elements like `<img>` must close themselves with a trailing `/`, like `<img... />`, while "never" means that they must close themselves with a `</img>` closing tag. If you want to turn this rule off entirely, use the value `false`, which is the default.

`tags-self-close` simply doesn't do anything, so that the default `false` value for `tag-self-close` is used. I assume the error with `'tag-self-close':'never'` comes from an html4-style `<img.../>` tag; if you want to allow these tags and disallow the alternative, use the value "always".

It's very difficult to explain this option both concisely and clearly. I may try to rewrite the wiki entry again, but no guarantees that it will come out any better.
