### ISSUE TITLE
proposal: expand `id-class-no-ad` option to check for other common triggers

### ISSUE THREAD

**Issue by tesslins** [htmllint/htmllint#234]
I'd like to expand the `id-class-no-ad` rule be expanded to also check for 'banner' and 'social' since those are very common ad-block triggers. This can be done in one of three ways: 
- add to the regex in the current rule
- add new phrase-specific rules (ie `id-class-no-banner`)
- add a single more general `id-class-adblocker` rule. 
The last option is my personal first choice but I'm open to any of the three.

**Comment by mlochbaum** [comment]
Thank you for this suggestion. I've added "banner" and "social" to the regex in `id-class-no-ad`, and fixed the error message so it indicates which word is not allowed and points to it (not just the entire attribute value).

I would prefer the name `id-class-adblocker` rather than `id-class-no-ad`, but I don't think it's worth inconveniencing anyone who has settings for `id-class-no-ad`. If htmllint ever gets a migration process I'll change it.
