### ISSUE TITLE
indent-style: "tabs" allow spaces after tabs with index-width-cont 

### ISSUE THREAD

**Issue by miltonhowe** [htmllint/htmllint#237]
I am using Webstorm with tab indents and have the `Align Attributes` tab checked in `Code Style -> HTML`.

The problem is for tags with names which do not cause the first attribute to land exactly on a tab stop, any attributes on following lines get lined up with it by appending spaces.

I would like to suggest a modification to `index-with-cont` or else a new rule which would exempt those lines from tripping the rule forbidding mixing tabs and spaces.

**Comment by krike** [comment]
any date on the release? Spended some time figuring why it wasn't working because it is mentioned in the documentation so I thought this was already available.

**Comment by mlochbaum** [comment]
`indent-width-cont` does work in the latest release (0.7.2). It just doesn't do anything useful for files with tabs. (The documentation could use some clarification based on this and the other fix to `indent-width-cont`, though).

I don't want to release `tag-req-attr` as it is--I think it needs a little more polishing. If it's too long and I still haven't worked on that I'll mess around with git to exclude it though. I won't give a date for a release because history has shown that's even less useful that not saying anything.

The fact that the wiki reflects the current development version and not the latest release is unfortunate. I don't have a good solution for that now.

**Comment by krike** [comment]
yes I understand about not giving a date. But if it should work in the latest version then I'm not sure why it is not working for me as I am using spaces and not tabs. I will debug some more and open a new issue if I can reproduce it correctly.

And if I can make a suggestion about the Wiki, You could specify if the config attribute is still being worked on. Just next to the the title you could add WIP or Beta, ... or using a colored title. But at least people will know they can or cannot use it yet :)
