### ISSUE TITLE
Setting attr-name-style to false does not work

### ISSUE THREAD

**Issue by krike** [htmllint/htmllint#240]
in my .htmllintrc I have `"attr-name-style": false,` 
but still I get the error `(E011), line 20, col 37, value must match the format: dash`

This is the HTML:
`<body data-pagetype="map" class="{{mapClass}}">`

I'm using twig and if I change the `{{mapClass}}` to a regular class it does seem to work. Which is strange since it is the attribute name I try to set a rule for or am I mistaken? even then if I set it to false I expect not the dash format to be enforced.

also when setting it to "none" it throws an error

**Comment by mlochbaum** [comment]
The error is coming from the `class-style` rule and not `attr-name-style`. You can look up the error code at [Option by Error Code](https://github.com/htmllint/htmllint/wiki/Option-by-Error-Code), which might help in situations like this.

This error message was changed in version 0.7.0 to use something more descriptive than "value"--in this case, it would be "class". If you can upgrade to 0.7.0 or later I definitely recommend it. It's less confusing in a lot of ways.

The settings for id and class style are kind of weird. See [`class-style`](https://github.com/htmllint/htmllint/wiki/Options#class-style). Essentially, `id-class-style` can control both but there's a special option "none" just for `class-style`. "none" isn't a format specifier and shouldn't have been listed with the rest at the top of the options page. I've removed it.

The easiest solution to your problem is likely to set `id-class-style` to `false`. But it's probably better to just exclude things in double braces--see [`id-class-ignore-regex`](https://github.com/htmllint/htmllint/wiki/Options#id-class-ignore-regex).

**Comment by krike** [comment]
I did use `id-class-ignore-regex` and yes that fixed the problem. thank you
