### ISSUE TITLE
some rules don't work well for html fragments

### ISSUE THREAD

**Issue by coalman** [htmllint/htmllint#99]
Some rules like `doctype-first` don't work for html fragments. This was originally by design, but there has been some friction in using them with our interfaces. The user has to write multiple configurations, one for html fragment and another for html documents.

Perhaps documenting the best practice for this with each interface or making it easier to combine configurations.

**Comment by mlochbaum** [comment]
If you make a `fragment` template that blanks the appropriate rules, you can apply that configuration after the other configurations. Something like that should be included in htmllint.

**Comment by glen-84** [comment]
How about changing these rules so that they only apply when other elements are present?

For example, doctype-first would only be required if the file includes a `<head>` and/or `<body>` element.

**Comment by mlochbaum** [comment]
I looked through all the rules and it turns out that `doctype-first` is the only one that breaks on fragments. All the others are properties of specific tags or other elements and not of the whole document (like `head-req-title`, which only applies if there is a `head` element).

A test for `doctype-first` like the one you recommend is somewhat confusing, and also slow if there are many top-level tags in the document (granted, that shouldn't happen for anything but a fragment). Given that `doctype-first` is off by default anyway, I don't think it's necessary.

I'm closing this issue because I think it doesn't need to be addressed based on the above. If you disagree, comment here and I'll reopen it.

**Comment by yvanavermaet** [comment]
@mlochbaum I do agree with the issue. This is one of the reasons we don't have doctype-first enabled. If the head-req-title only applies when there is a head-element in the file, why not do the same for doctype-first? If the html-element is present ==> check if there is a doctype.

**Comment by glen-84** [comment]
> A test for doctype-first like the one you recommend is somewhat confusing

How so? You wouldn't use a doctype without a `head`, would you?

> ... and also slow if there are many top-level tags in the document

Really? I have no idea how this tool works, but I'd expect it to be a simple check (even once per top-level tag would be fast).

> Given that doctype-first is off by default anyway, I don't think it's necessary.

It just makes the rule useless for most people who use fragments/partials in addition to "layouts".

**Comment by mlochbaum** [comment]
The core of my complaints about the suggested rule is that it doesn't match the architecture of the rest of htmllint. For every other rule, the error comes from the element that is checked, or possibly a parent element. For this rule, it would come from both the first tag (which is not `html`) and some other `head` or `body` tag in the document. This is confusing because a change like wrapping a fragment in a `head` tag triggers the rule even though the first tag wasn't a doctype before.

Checking all the top-level tags wouldn't cause a noticeable delay on its own, but it's slower than a rule should be. htmllint is set up so that the dom tree is only traversed once, and having each rule do its own traversal would be much slower. However, I found that it's possible to use the same rule to check for a `head` or `body` tag later in the document and throw the appropriate error there, so this is not actually an issue.

I still feel that the programmer should know whether a document is a fragment or not and pass the right option appropriately. Actually I find it a bit strange that anyone would lint both fragments and full documents in the same run. But I can add an option to use the tag checks. I still want to have it always check if `doctype-first` is `true`, so I'll make a new option for context-aware checking. Is "smart" a good option name?

**Comment by glen-84** [comment]
@mlochbaum,

It looks like html/head/body are optional tags (see [here](http://stackoverflow.com/questions/5641997/is-it-necessary-to-write-head-body-and-html-tags)), so perhaps this is not the best solution.

I'll probably just leave this rule disabled.

**Comment by mlochbaum** [comment]
It still makes sense for users that have a policy of using those tags, and isn't hard to implement. I'll probably add it as a new option to `doctype-first` in the next few days.

**Comment by mlochbaum** [comment]
That was an odd way to spell "next few months".
